config/routes.rb
NewApp::Application.routes.draw do

  devise_for :users

  resources :roles

  root :to => "homepage#index"
  resources :player_records

  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :age, :country, :dob, :name, :type_of_sport
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  load_and_authorize_resource
  # skip_authorize_resource :only => :show
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
     @player = Player.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br />
    <%= f.date_select :dob ,start_year: 1975%>
  </div>
  <div class="field">
    <%= f.label :type_of_sport %><br />
    <%= f.text_field :type_of_sport %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<div>
<h1>Listing players</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Dob</th>
    <th>Age</th>
    <th>Type of sport</th>
    <th>Country</th>
    <% if can? :read ,:all%><th>Actions</th><%end%>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.dob %></td>
    <td><%=((Time.now - player.dob.to_time)/(365*24*60*60)).round%>&nbsp;years</td>
    <td><%= player.type_of_sport %></td>
    <td><%= player.country %></td>
    <% if can? :read ,:all%><td><%= link_to 'Show', player %><%end%>
    <% if can? :update,:delete, Player%>
    <%= link_to 'Edit', edit_player_path(player) %>
    <%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %><%end%></td>
  </tr>
<% end %>
</table>
<br/>
<div id="new-player">
<% if can? :update,:delete, Player%>
<%= link_to 'Add Player Record', new_player_record_path %>
<%end%>
</div>


</div>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>

  <b>Type of sport:</b>
  <%= @player.type_of_sport %>

  <b>Country:</b>
  <%= @player.country %>
</p>
<p>
<% record = PlayerRecord.find_by_player_id(@player.id)%>
<% if !record.nil?%>
<%=record.records%>
<%else%>
Not Available
<%end%>
</p>

<% if can? :update,:delete, Player%>
<%= link_to 'Edit', edit_player_path(@player) %> 
<%end%>
<%= link_to 'Back', players_path %>