config/routes.rb
NewApp::Application.routes.draw do

  devise_for :users

  resources :roles

  root :to => "homepage#index"
  resources :player_records

  resources :players

end

app/models/player_record.rb
class PlayerRecord < ActiveRecord::Base
  belongs_to :player
  attr_accessible :records,:player_id
end

app/controllers/player_records_controller.rb
class PlayerRecordsController < ApplicationController
  # GET /player_records
  # GET /player_records.json
  load_and_authorize_resource
  skip_authorize_resource :only => :show
  def index
    @player_records = PlayerRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @player_records }
    end
  end

  # GET /player_records/1
  # GET /player_records/1.json
  def show
    @player_record = PlayerRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player_record }
    end
  end

  # GET /player_records/new
  # GET /player_records/new.json
  def new
    @player_record = PlayerRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player_record }
    end
  end

  # GET /player_records/1/edit
  def edit
    @player_record = PlayerRecord.find(params[:id])
  end

  # POST /player_records
  # POST /player_records.json
  def create
    @player_record = PlayerRecord.new(params[:player_record])

    respond_to do |format|
      if @player_record.save
        format.html { redirect_to @player_record, notice: 'Player record was successfully created.' }
        format.json { render json: @player_record, status: :created, location: @player_record }
      else
        format.html { render action: "new" }
        format.json { render json: @player_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /player_records/1
  # PUT /player_records/1.json
  def update
    @player_record = PlayerRecord.find(params[:id])
    respond_to do |format|
      if @player_record.update_attributes(params[:player_record])
        format.html { redirect_to @player_record, notice: 'Player record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_records/1
  # DELETE /player_records/1.json
  def destroy
    @player_record = PlayerRecord.find(params[:id])
    @player_record.destroy

    respond_to do |format|
      format.html { redirect_to player_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/player_records_helper.rb
module PlayerRecordsHelper
end

app/views/player_records/_form.html.erb
<%= form_for(@player_record) do |f| %>
  <% if @player_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_record.errors.count, "error") %> prohibited this player_record from being saved:</h2>

      <ul>
      <% @player_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :records %><br />
    <%= f.text_field :records %>
  </div>
  <div class="field">
    <%= f.label :player %><br />
    <%= f.collection_select(:player_id,Player.all,:id,:name,{:include_blank => ''}) %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_records/edit.html.erb
<h1>Editing player_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_record %> |
<%= link_to 'Back', player_records_path %>

app/views/player_records/index.html.erb
<h1>Listing player_records</h1>
<table>
  <tr>
    <th>Records</th>
    <th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @player_records.each do |player_record| %>
  <tr>
    <td><%= player_record.records %></td>
    <td><%= player_record.player_id %></td>
    <td>
    <% if can? :update,:delete, PlayerRecord%>
    <%= link_to 'Edit', edit_player_record_path(player_record) %>
    <%= link_to 'Destroy', player_record, method: :delete, data: { confirm: 'Are you sure?' } %><%end%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player record', new_player_record_path %>

app/views/player_records/new.html.erb
<h1>New player_record</h1>

<%= render 'form' %>

<%= link_to 'Back', player_records_path %>

app/views/player_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Records:</b>
  <%= @player_record.records %>
</p>

<p>
  <b>Player:</b>
  <%= @player_record.player_id %>
</p>

<% if can? :update,:delete, Player%>
<%= link_to 'Edit', edit_player_record_path(@player_record) %> |
<%end%>
<%= link_to 'Back', player_records_path %>